# ----------------------------------------- Helm chart removal
-
- name: Helm chart uninstall
  block:

  - name: Remove secret_generator helm chart
    shell: helm -n "{{ secret_generator_namespace }}" uninstall {{ secret_generator_helm_release }}
    args:
      chdir: /tmp
    run_once: true

#
#  - name: Remove secret_generator namespace
#    k8s:
#      state: absent
#      definition:
#        api_version: v1
#        kind: Namespace
#        metadata:
#          name: "{{ secret_generator_namespace }}"
  run_once: true
