# Copyright (C) 2023 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.



# ----------------------------------------- Deployment

- name: Create metallb namespace
  k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ metallb_namespace }}"
        labels:
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/warn: privileged
  run_once: true

- name: Setup value file
  template:
    src: "values.yaml.j2"
    dest: /tmp/metallb_values.yaml
  run_once: true


- name: Copy configuration file
  template:
    src: metallb-config.yaml.j2
    dest: /tmp/metallb-config.yaml

- name: Deploy metallb helm chart
  kubernetes.core.helm:
    release_name: metallb
    release_namespace: "{{ metallb_namespace }}"
    chart_ref: "{{ metallb_helm_chart_url }}"
    values_files:
      - /tmp/metallb_values.yaml
  run_once: true

- name: Configure metallb (May wait for the controller webhook to be ready)
  k8s:
    state: present
    src: "/tmp/metallb-config.yaml"
  retries: 30   # NB: May take long time to load image
  delay: 5
  register: result
  until: not result.failed
