
# ---------------------------------------------------------------------------
- name: API server clean configuration
  block:
  - name: Unconfigure kube api server (1/4)
    lineinfile:
      path: /etc/kubernetes/manifests/kube-apiserver.yaml
      regexp: "{{ item.regexp }}"
      state: absent
    with_items:
    - { regexp: '^.*authentication-token-webhook-config-file.*' }
    - { regexp: '^.*authentication-token-webhook-cache-ttl.*' }
    - { regexp: '^.*dnsPolicy:.*' }


  - name: Unconfigure kube api server (3/4)
    blockinfile:
      path: /etc/kubernetes/manifests/kube-apiserver.yaml
      marker: "# Ansible skas config 1/4 hacking {mark}"
      state: absent

  - name: Unconfigure kube api server (4/3)
    blockinfile:
      path: /etc/kubernetes/manifests/kube-apiserver.yaml
      marker: "# Ansible skas config 2/4 hacking {mark}"
      state: absent

  - name: Wait for api server to be back again
    wait_for:
      port: 6443
      state: started
      timeout: 300
      delay: 15

  when: skas_configure_apiserver

- name: Remove skas working folder
  file:
    state: absent
    path: /etc/kubernetes/skas



# ----------------------------------------- Helm chart removal
-
- name: Helm chart uninstall
  block:
  - name: Remove skas helm chart
    kubernetes.core.helm:
      release_state: absent
      release_name: "{{ skas_helm_release }}"
      release_namespace: "{{ skas_namespace}}"
      create_namespace: false
      chart_ref: "{{ skas_helm_chart_url }}"
      values_files:
        - /tmp/skas_values.yaml
    run_once: true


  - name: Remove skas namespace
    k8s:
      state: absent
      definition:
        api_version: v1
        kind: Namespace
        metadata:
          name: "{{ skas_namespace }}"
    run_once: true
  when: skas_deploy_helm_chart
