# Copyright (C) 2020 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


type: map
mapping:
  "k8s":
    type: map
    required: true
    mapping:
      "helm_deployments":
        type: seq
        required: true
        sequence:
        - type: map
          mapping:
            "disabled": { type: bool, required: False }
            "name": { type: str, required: true }
            "repo": { type: str, required: false }
            "chart": { type: str, required: true }
            "namespace": { type: str, required: true }    # This namespace will be created if unexisting. But, it will NOT be deleted when state=="absent" 
            "version": { type: str, required: false }
            "values": { type: any, required: false }
            "state": { type: str, required: false, enum: ["present", "absent", "latest" ] } # Default: present. latest will upgrade
              
          