# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


- name: Install k8s ansible module required package (Redhat)
  yum: name=python2-openshift state=present
  when: ansible_os_family == "RedHat"
- name: Install k8s ansible module required package (Debian)
  block:
    - name: Install python3-pip with apt
      ansible.builtin.apt:
        name: python3-pip
        state: present
    - name: Pip install k8s required modules
      ansible.builtin.pip:
        name:
          - openshift==0.13.1
          - pyyaml==5.3.1
          - kubernetes==24.2.0
         # NB: Above values are know to work with kubespray 2.18.1 / k8s v1.22.8 on ubuntu 20.04
         # For example, kubernetes==25.3.0 will fail for next step in such context:
         # failed: [m0] (item=m0) => {"ansible_loop_var": "item", "changed": false, "item": "m0", "msg": "Failed to get client due to openssl_md5() takes at most 1 argument (2 given)"}
        extra_args: "{{ cert_manager_pip_extra_args | default(omit) }}"
  when: ansible_os_family == "Debian"

- name: Copy definition file
  template:
    src: cert_manager_{{ cert_manager_version }}.yaml
    dest: /tmp/cert_manager.yaml  

- name: Install cert_manager
  k8s:
    state: present
    src: "/tmp/cert_manager.yaml"
  
- name: Wait for cert-manager running
  k8s_info:
    kind: Pod
    api_version: v1
    namespace: cert-manager
    label_selectors:
    - app=cert-manager
    field_selectors:
    - status.phase=Running
  register: k8s_result
  retries: 60
  delay: 3
  until: k8s_result.resources is defined and k8s_result.resources|length > 0
  
- name: Wait for cert-manager-cainjector running
  k8s_info:
    kind: Pod
    api_version: v1
    namespace: cert-manager
    label_selectors:
    - app=cainjector
    field_selectors:
    - status.phase=Running
  register: k8s_result
  retries: 30
  delay: 3
  until: k8s_result.resources is defined and k8s_result.resources|length > 0
  
- name: Wait for cert-manager-webhook running
  k8s_info:
    kind: Pod
    api_version: v1
    namespace: cert-manager
    label_selectors:
    - app=webhook
    field_selectors:
    - status.phase=Running
  register: k8s_result
  retries: 30
  delay: 3
  until: k8s_result.resources is defined and k8s_result.resources|length > 0

- name: Pause 30sec for the webhook to be ready
  pause:
    seconds: 30  
  
- name: Copy cluster_issuers
  template:
    src: cluster_issuers.yaml.j2
    dest: /tmp/cluster_issuers.yaml  

- name: Install cluster_issuers
  k8s:
    state: present
    src: "/tmp/cluster_issuers.yaml"  
    