# Copyright (C) 2020 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


type: map
mapping:
  "k8s":
    type: map
    required: true
    mapping:
      "skas":
        type: map
        required: true
        mapping:
          "disabled": { type: bool, required: False }
          "repo_id": { type: str, required: true }
          auth_webhook_url: { type: str, required: false }    # Default: https://skas-auth.skas-system.svc/v1/tokenReview
          auth_cert_name: { type: str, required: false }      # Default skas-auth-cert
          namespace: { type: str, required: false }         # Default: skas-system
          helm_release_name: { type: str, required: false }   # Default: skas
          helm_values: { type: any, required: false }        # Default: ""
          users_helm_release_name: { type: str, required: false }   # Default: skusers
          users_helm_values: { type: any, required: false }    # Default: ""
          ingress_nginx_host: { type: str, required: false }
          cluster_issuer: { type: str, required: false }
          replica_count: { type: int, required: false }
          enable_login_service: { type: bool, required: false }
          control_plane: { type: bool, required: false }
          kubeconfig:
            type: map
            required: false
            mapping:
              context: { type: str, required: true }
              api_server_url: { type: str, required: true }

