---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
{% for range in  metallb.external_ip_ranges %}
    - {{range.first}}-{{range.last}}
{%  endfor %}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-pool
  namespace: metallb-system

{% if metallb.dashboard_ip is defined %}
---
apiVersion: v1
kind: Service
metadata:  
  namespace: kube-system
  name: dashboard-lb
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{metallb.dashboard_ip }}
spec:
  selector:    
    k8s-app: kubernetes-dashboard
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8443
{% endif %}
      
      