# Copyright (C) 2023 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.



# ----------------------------------------- Deployment

- name: Create cert-manager namespace
  k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ cert_manager_namespace }}"
  run_once: true

- name: Copy preset file
  template:
    src: cert-manager-preset.yaml.j2
    dest: /tmp/cert-manager-preset.yaml
  run_once: true

- name: Apply preset file
  k8s:
    state: present
    src: "/tmp/cert-manager-preset.yaml"
  run_once: true

- name: Setup value file
  template:
    src: "values.yaml.j2"
    dest: /tmp/cert_manager_values.yaml
  run_once: true


- name: Deploy cert-manager helm chart
  kubernetes.core.helm:
    release_name: cert-manager
    release_namespace: "{{ cert_manager_namespace }}"
    chart_ref: "{{ cert_manager_helm_chart_url }}"
    values_files:
      - /tmp/cert_manager_values.yaml
  run_once: true
